server:
  port: 8080


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.26.185.75:3306/seckill?characterEncoding=utf8&serverTimezone=UTC&amp&useSSL=false
    username: root
    password: 123456
  redis:
    database: 0
    port: 6379
    host: 120.26.185.75


mybatis:
  mapper-locations: classpath:com/qmh/mapper/*.xml
  type-aliases-package: com.qmh.entity


